spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/limbus?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: dlwoghd98
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/limbus
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5

  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: none
    properties:
      hibernate:
      # show_sql: true
      format_sql: true
      use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace